// /src/shared/corridors.ts
import type { Corridor } from './types';

export const corridors: Corridor[] = [
  {
    id: 'liberia-edmonton-2008',
    originCountry: 'Liberia',
    originCity: 'via Buduburam refugee camp, Ghana',
    originLatLng: [5.6037, -0.1870],
    arrivalYear: 2008,
    canadianCity: 'Edmonton',
    canadianLatLng: [53.5461, -113.4938],
    context: 'You fled the second Liberian civil war. Your kid was born in the camp. You arrived in Edmonton through the federal Resettlement Assistance Program when he was five.',
    realCorridorNote: 'Liberian families were among refugee and immigrant communities resettling in Alberta after the second Liberian civil war (1999-2003) under Canada\'s federal Resettlement Assistance Program. CIC records show 647 permanent residents from Liberia admitted to all of Canada from 2003-2010; 2,485 people reported Liberian ethnic origin in Canada in the 2016 Census. Source: CIC Facts and Figures 2010; Statistics Canada 2016 Census.',
    hasFamousPlayer: true,
  },
  {
    id: 'jamaica-brampton-2000',
    originCountry: 'Jamaica',
    originCity: 'Kingston',
    originLatLng: [17.9714, -76.7936],
    arrivalYear: 2000,
    canadianCity: 'Brampton',
    canadianLatLng: [43.7315, -79.7624],
    context: 'You came from Kingston in the late 1990s wave. You settled in Brampton because cousins were already there. Your kid started kicking a ball before he could write his name.',
    realCorridorNote: '30,960 residents reported Jamaican ethnic origin in Brampton in the 2021 Census, with 22,210 born in Jamaica. The Caribbean diaspora corridor produced more Canadian national-team players than any official developmental pathway. Source: Statistics Canada 2021 Census Profile, Brampton (CY).',
    hasFamousPlayer: true,
  },
  {
    id: 'punjab-brampton-2010',
    originCountry: 'India',
    originCity: 'Punjab',
    originLatLng: [30.7333, 76.7794],
    arrivalYear: 2010,
    canadianCity: 'Brampton',
    canadianLatLng: [43.7315, -79.7624],
    context: 'You came from Punjab on a permanent residence application. Your kid plays cricket at school and football on weekends. The neighborhood team is half Punjabi, half Caribbean.',
    realCorridorNote: 'Brampton had 340,815 South Asian residents in the 2021 Census - 52.42% of the city - with 141,005 reporting Punjabi as their mother tongue, the city\'s leading non-official language. Despite being one of Canada\'s largest immigrant corridors, no Punjabi-Canadian has appeared on a Canada men\'s senior national team roster, though Punjabi-Canadian players exist in Canada\'s youth and professional pathways. Source: Statistics Canada 2021 Census Profile, Brampton (CY).',
    hasFamousPlayer: false,
  },
  {
    id: 'syria-mississauga-2016',
    originCountry: 'Syria',
    originCity: 'Aleppo',
    originLatLng: [36.2021, 37.1343],
    arrivalYear: 2016,
    canadianCity: 'Mississauga',
    canadianLatLng: [43.5890, -79.6441],
    context: 'You arrived in early 2016 as part of the Syrian resettlement program. Your kid was eight when you landed. He learned English on the playground and football in the parking lot.',
    realCorridorNote: 'Canada welcomed 25,555 Syrian refugees between December 2015 and the end of February 2016 under Operation Syrian Refugees, with the total commitment reaching 26,172 (14,994 government-assisted, 2,224 blended visa office-referred, 8,954 privately sponsored). A significant share resettled in the Greater Toronto Area. Source: IRCC Operation Syrian Refugees; Statistics Canada.',
    hasFamousPlayer: false,
  },
];
