import type { Corridor } from './types';

export const corridors: Corridor[] = [
  {
    id: 'liberia-edmonton-2008',
    originCountry: 'Liberia',
    originCity: 'via Buduburam refugee camp, Ghana',
    originLatLng: [5.6037, -0.1870],
    arrivalYear: 2008,
    canadianCity: 'Edmonton',
    canadianLatLng: [53.5461, -113.4938],
    context: 'You fled the second Liberian civil war. Your kid was born in the camp. You arrived in Edmonton through refugee resettlement when he was five.',
    realCorridorNote: 'Liberian resettlement to Alberta was real, but I could not verify the precise "2,500 Liberian refugees to Alberta between 2003 and 2010" figure from an accessible IRCC/StatsCan source. Keep this as an approximate/local research note until the dataset is in hand.',
    hasFamousPlayer: true,
  },
  {
    id: 'jamaica-brampton-2000',
    originCountry: 'Jamaica',
    originCity: 'Kingston',
    originLatLng: [17.9714, -76.7936],
    arrivalYear: 2000,
    canadianCity: 'Brampton',
    canadianLatLng: [43.7315, -79.7624],
    context: 'You came from Kingston in the late 1990s wave. You settled in Brampton because cousins were already there. Your kid started kicking a ball before he could write his name.',
    realCorridorNote: 'Brampton is one of Canada\'s major Jamaican-Canadian centres. Statistics Canada\'s 2021 Census profile lists 30,960 residents reporting Jamaican ethnic or cultural origin.',
    hasFamousPlayer: true,
  },
  {
    id: 'punjab-brampton-2010',
    originCountry: 'India',
    originCity: 'Punjab',
    originLatLng: [30.7333, 76.7794],
    arrivalYear: 2010,
    canadianCity: 'Brampton',
    canadianLatLng: [43.7315, -79.7624],
    context: 'You came from Punjab on a permanent residence application. Your kid plays cricket at school and football on weekends. The neighborhood team is half Punjabi, half Caribbean.',
    realCorridorNote: 'Brampton has one of Canada\'s largest South Asian communities. Statistics Canada\'s 2021 Census profile lists 340,815 South Asian residents and 57,075 residents reporting Punjabi ethnic or cultural origin.',
    hasFamousPlayer: false,
  },
  {
    id: 'syria-mississauga-2016',
    originCountry: 'Syria',
    originCity: 'Aleppo',
    originLatLng: [36.2021, 37.1343],
    arrivalYear: 2016,
    canadianCity: 'Mississauga',
    canadianLatLng: [43.5890, -79.6441],
    context: 'You arrived in early 2016 as part of the Syrian resettlement program. Your kid was eight when you landed. He learned English on the playground and football in the parking lot.',
    realCorridorNote: 'Canada completed its commitment to welcome 25,000 Syrian refugees by the end of February 2016; IRCC\'s published total for that initial commitment is 26,172 people.',
    hasFamousPlayer: false,
  },
];
