import type { FamousPlayer } from './types';

export const famousPlayers: FamousPlayer[] = [
  {
    id: 'davies',
    name: 'Alphonso Davies',
    birthplace: 'Buduburam refugee camp, Ghana',
    birthLatLng: [5.6037, -0.1870],
    transitPoint: 'Edmonton',
    transitLatLng: [53.5461, -113.4938],
    canadianCity: 'Edmonton',
    canadianLatLng: [53.5461, -113.4938],
    finalLatLng: [48.1351, 11.5820],
    arrivalYear: 2005,
    pathway: 'Free Footie -> Vancouver Whitecaps -> Bayern Munich',
    bypassedSystem: true,
    story: 'Born in a Ghanaian refugee camp to parents fleeing Liberia\'s civil war. Resettled to Edmonton at five. Discovered through Free Footie, a free after-school program that exists because the official Canadian soccer pipeline costs thousands of dollars a year.',
  },
  {
    id: 'david',
    name: 'Jonathan David',
    birthplace: 'New York City, United States',
    birthLatLng: [40.6782, -73.9442],
    transitPoint: 'Ottawa',
    transitLatLng: [45.4215, -75.6972],
    canadianCity: 'Ottawa',
    canadianLatLng: [45.4215, -75.6972],
    finalLatLng: [45.0703, 7.6869],
    arrivalYear: 2006,
    pathway: 'Gloucester Dragons -> Ottawa Gloucester Hornets -> Ottawa Internationals -> Gent -> Lille -> Juventus',
    bypassedSystem: true,
    story: 'Born in New York City to Haitian parents, moved to Haiti as a baby, and immigrated to Ottawa at six. Signed from Ottawa youth soccer into Belgium with Gent at seventeen. The elite Canadian pipeline did not produce him.',
  },
  {
    id: 'larin',
    name: 'Cyle Larin',
    birthplace: 'Brampton, Ontario',
    birthLatLng: [43.7315, -79.7624],
    canadianCity: 'Brampton',
    canadianLatLng: [43.7315, -79.7624],
    finalLatLng: [39.5696, 2.6502],
    arrivalYear: 1995,
    pathway: 'Sigma FC -> UConn (NCAA) -> Orlando City -> Besiktas -> Mallorca',
    bypassedSystem: true,
    story: 'Born in Brampton to a Jamaican family. Came up through Sigma FC and UConn, then became the first overall pick in the 2015 MLS SuperDraft. His route ran through private academy and NCAA scholarship channels more than through a public Canadian pipeline.',
  },
  {
    id: 'tajon-buchanan',
    name: 'Tajon Buchanan',
    birthplace: 'Brampton, Ontario',
    birthLatLng: [43.7315, -79.7624],
    canadianCity: 'Brampton',
    canadianLatLng: [43.7315, -79.7624],
    finalLatLng: [39.9457, -0.0372],
    arrivalYear: 1999,
    pathway: 'Brampton YSC -> Mississauga Falcons -> Real Colorado -> Syracuse (NCAA) -> New England Revolution -> Club Brugge -> Inter Milan -> Villarreal',
    bypassedSystem: true,
    story: 'Born and raised in Brampton. Moved into the U.S. academy and NCAA route before reaching MLS and Europe. His path shows how often Canadian talent has needed a detour outside the local system.',
  },
  {
    id: 'osorio',
    name: 'Jonathan Osorio',
    birthplace: 'Toronto, Ontario',
    birthLatLng: [43.6532, -79.3832],
    canadianCity: 'Toronto',
    canadianLatLng: [43.6532, -79.3832],
    arrivalYear: 1992,
    pathway: 'Toronto FC Academy -> Toronto FC first team',
    bypassedSystem: false,
    story: 'Born in Toronto to Colombian parents. The rare clean Canadian academy product: came up through Toronto FC\'s system and stayed.',
  },
  {
    id: 'hutchinson',
    name: 'Atiba Hutchinson',
    birthplace: 'Brampton, Ontario',
    birthLatLng: [43.7315, -79.7624],
    canadianCity: 'Brampton',
    canadianLatLng: [43.7315, -79.7624],
    finalLatLng: [41.0082, 28.9784],
    arrivalYear: 1983,
    pathway: 'Brampton YSC -> North Scarborough SC -> Woodbridge Strikers -> York Region Shooters -> Toronto Lynx -> Oster -> Helsingborg -> Copenhagen -> PSV -> Besiktas',
    bypassedSystem: true,
    story: 'Born in Brampton to Trinidadian parents. The greatest Canadian midfielder of his generation reached his prime through Sweden, Denmark, the Netherlands, and Turkey after Canada had little more to offer him.',
  },
  {
    id: 'eustaquio',
    name: 'Stephen Eustaquio',
    birthplace: 'Leamington, Ontario',
    birthLatLng: [42.0529, -82.5990],
    transitPoint: 'Portugal (returned as a child)',
    transitLatLng: [41.1579, -8.6291],
    canadianCity: 'Leamington',
    canadianLatLng: [42.0529, -82.5990],
    finalLatLng: [41.1579, -8.6291],
    arrivalYear: 1996,
    pathway: 'Nazarenos -> Uniao de Leiria -> Torreense -> Leixoes -> Chaves -> Cruz Azul -> Pacos de Ferreira -> Porto',
    bypassedSystem: true,
    story: 'Born in Leamington, Ontario, to Portuguese parents. Family returned to Portugal during his childhood, and he developed through Portuguese clubs before Canada later capped him.',
  },
  {
    id: 'kone',
    name: 'Ismael Kone',
    birthplace: 'Abidjan, Cote d\'Ivoire',
    birthLatLng: [5.3600, -4.0083],
    canadianCity: 'Montreal',
    canadianLatLng: [45.5019, -73.5674],
    finalLatLng: [44.5380, 10.9356],
    arrivalYear: 2010,
    pathway: 'AS Notre-Dame-de-Grace -> CS Saint-Laurent -> CF Montreal -> Watford -> Marseille -> Sassuolo',
    bypassedSystem: true,
    partialBypass: true,
    story: 'Born in Abidjan and arrived in Montreal as a child. Developed through local Quebec clubs before CF Montreal, then moved quickly into England, France, and Italy.',
  },
  {
    id: 'hoilett',
    name: 'Junior Hoilett',
    birthplace: 'Brampton, Ontario',
    birthLatLng: [43.7315, -79.7624],
    canadianCity: 'Brampton',
    canadianLatLng: [43.7315, -79.7624],
    finalLatLng: [53.7500, -2.4833],
    arrivalYear: 1990,
    pathway: 'Brampton YSC -> CS Azzurri -> Oakville SC -> Blackburn Rovers academy -> QPR -> Cardiff City -> Reading',
    bypassedSystem: true,
    story: 'Born in Brampton to Jamaican parents. Signed for Blackburn Rovers in 2003 at thirteen after youth soccer in the GTA, then made his Premier League debut in England.',
  },
  {
    id: 'sinclair',
    name: 'Christine Sinclair',
    birthplace: 'Burnaby, British Columbia',
    birthLatLng: [49.2488, -122.9805],
    canadianCity: 'Burnaby',
    canadianLatLng: [49.2488, -122.9805],
    finalLatLng: [45.5152, -122.6784],
    arrivalYear: 1983,
    pathway: 'Burnaby youth clubs -> University of Portland (NCAA) -> Portland Thorns (NWSL)',
    bypassedSystem: true,
    story: 'Canada\'s all-time leading international goal-scorer, men\'s or women\'s. Came up through youth clubs and NCAA soccer because Canada had no equivalent women\'s professional structure for her generation.',
  },
  {
    id: 'kadeisha-buchanan',
    name: 'Kadeisha Buchanan',
    birthplace: 'Brampton, Ontario',
    birthLatLng: [43.7315, -79.7624],
    canadianCity: 'Brampton',
    canadianLatLng: [43.7315, -79.7624],
    finalLatLng: [48.1351, 11.5820],
    arrivalYear: 1995,
    pathway: 'Brampton youth -> West Virginia University (NCAA) -> Lyon -> Chelsea -> Bayern Munich',
    bypassedSystem: true,
    story: 'Born in Brampton to Jamaican parents, from the same diaspora corridor as several Canadian men\'s stars. NCAA soccer was the viable bridge to the professional game.',
  },
  {
    id: 'lawrence',
    name: 'Ashley Lawrence',
    birthplace: 'Toronto, Ontario',
    birthLatLng: [43.6532, -79.3832],
    canadianCity: 'Brampton-area corridor',
    canadianLatLng: [43.7315, -79.7624],
    finalLatLng: [45.7640, 4.8357],
    arrivalYear: 1995,
    pathway: 'Brams United -> Erin Mills SC -> West Virginia University (NCAA) -> PSG -> Chelsea -> OL Lyonnes',
    bypassedSystem: true,
    story: 'Born in Toronto and raised through the Brampton-area youth soccer corridor. NCAA scholarship to West Virginia led to PSG, Chelsea, and Lyon.',
  },
  {
    id: 'grosso',
    name: 'Julia Grosso',
    birthplace: 'Vancouver, British Columbia',
    birthLatLng: [49.2827, -123.1207],
    canadianCity: 'Vancouver',
    canadianLatLng: [49.2827, -123.1207],
    finalLatLng: [41.8781, -87.6298],
    arrivalYear: 1999,
    pathway: 'Vancouver youth -> University of Texas (NCAA) -> Juventus -> Chicago Stars',
    bypassedSystem: true,
    story: 'Born in Vancouver to an Italian family. Scored the gold-medal-winning penalty for Canada at Tokyo 2020. Her professional route, like many Canadian women of her generation, ran through U.S. college soccer.',
  },
];
