// /src/shared/players.ts
import type { FamousPlayer } from './types';

export const famousPlayers: FamousPlayer[] = [
  {
    id: 'davies',
    name: 'Alphonso Davies',
    corridorTag: 'liberian-edmonton',
    birthplace: 'Buduburam refugee camp, Ghana',
    birthLatLng: [5.6037, -0.1870],
    transitPoint: 'Edmonton',
    transitLatLng: [53.5461, -113.4938],
    canadianCity: 'Edmonton',
    canadianLatLng: [53.5461, -113.4938],
    finalLatLng: [48.1351, 11.5820],
    arrivalYear: 2005,
    pathway: 'Free Footie -> Edmonton Internationals -> Edmonton Strikers -> Vancouver Whitecaps Residency -> Bayern Munich',
    bypassedSystem: true,
    partialBypass: true,
    story: 'Born in a Ghanaian refugee camp to parents fleeing Liberia\'s civil war. Resettled to Edmonton at five. Discovered through Free Footie - a free after-school program that exists because the official Canadian soccer pipeline costs thousands of dollars a year. Whitecaps Residency picked him up at fourteen.',
  },
  {
    id: 'david',
    name: 'Jonathan David',
    corridorTag: 'haitian-montreal',
    birthplace: 'Brooklyn, New York',
    birthLatLng: [40.6782, -73.9442],
    transitPoint: 'Ottawa',
    transitLatLng: [45.4215, -75.6972],
    canadianCity: 'Ottawa',
    canadianLatLng: [45.4215, -75.6972],
    finalLatLng: [45.0703, 7.6869],
    arrivalYear: 2006,
    pathway: 'Gloucester Dragons -> Ottawa Gloucester Hornets -> Ottawa Internationals -> KAA Gent -> Lille -> Juventus',
    bypassedSystem: true,
    story: 'Born in Brooklyn to Haitian parents, raised in Ottawa from age six. Skipped MLS academies entirely. Signed directly from a community club in Ottawa to Belgian first division at seventeen. Moved to Juventus in 2025. Canadian system never developed him.',
  },
  {
    id: 'larin',
    name: 'Cyle Larin',
    corridorTag: 'jamaican-brampton',
    birthplace: 'Brampton, Ontario',
    birthLatLng: [43.7315, -79.7624],
    canadianCity: 'Brampton',
    canadianLatLng: [43.7315, -79.7624],
    finalLatLng: [50.9097, -1.4044],
    arrivalYear: 1995,
    pathway: 'Brampton YSC -> Sigma FC -> UConn (NCAA) -> Orlando City -> Besiktas -> Club Brugge -> Valladolid -> Mallorca -> Southampton (loan)',
    bypassedSystem: true,
    story: 'Born in Brampton to Jamaican immigrants. Came up through Sigma FC - a privately run Mississauga academy that exists specifically because the official OPDL system prices out most newcomer families. Drafted first overall in MLS via NCAA scholarship. Currently on loan at Southampton from Mallorca.',
  },
  {
    id: 'tajon-buchanan',
    name: 'Tajon Buchanan',
    corridorTag: 'jamaican-brampton',
    birthplace: 'Toronto area, raised in Brampton',
    birthLatLng: [43.7315, -79.7624],
    canadianCity: 'Brampton',
    canadianLatLng: [43.7315, -79.7624],
    finalLatLng: [39.9457, -0.0372],
    arrivalYear: 1999,
    pathway: 'Brampton YSC -> Mississauga Falcons -> Real Colorado -> Syracuse (NCAA) -> Sigma FC -> New England -> Club Brugge -> Inter Milan -> Villarreal',
    bypassedSystem: true,
    story: 'Raised in Brampton with Jamaican heritage. Left for Real Colorado as a teen, then NCAA at Syracuse, then Sigma FC senior side. Moved permanently to Villarreal in summer 2025. Bypassed the Canadian academy system entirely.',
  },
  {
    id: 'osorio',
    name: 'Jonathan Osorio',
    corridorTag: 'colombian-toronto',
    birthplace: 'Toronto, Ontario',
    birthLatLng: [43.6532, -79.3832],
    canadianCity: 'Toronto',
    canadianLatLng: [43.6532, -79.3832],
    arrivalYear: 1992,
    pathway: 'SC Toronto -> Club Nacional (Uruguay) -> Toronto FC Academy (Sept 2012) -> Toronto FC',
    bypassedSystem: true,
    partialBypass: true,
    story: 'Born in Toronto to Colombian parents. Often cited as a clean Toronto FC Academy product - but he actually trained at Club Nacional in Uruguay from 2010 to 2012 before TFC integrated him in September 2012, age 20. Even Canada\'s most-cited "system success story" came back from abroad.',
  },
  {
    id: 'hutchinson',
    name: 'Atiba Hutchinson',
    corridorTag: 'jamaican-brampton',
    birthplace: 'Brampton, Ontario',
    birthLatLng: [43.7315, -79.7624],
    canadianCity: 'Brampton',
    canadianLatLng: [43.7315, -79.7624],
    finalLatLng: [41.0082, 28.9784],
    arrivalYear: 1983,
    pathway: 'Brampton youth -> York Region Shooters -> Toronto Lynx (A-League) -> Osters IF (Sweden) -> Helsingborg -> FC Copenhagen -> PSV -> Besiktas',
    bypassedSystem: true,
    story: 'Born in Brampton to Trinidadian parents. The greatest Canadian midfielder of his generation, and Canadian football did not develop him - Sweden did, in his early twenties, after the Canadian system had nothing more to offer him. Retired in 2023.',
  },
  {
    id: 'eustaquio',
    name: 'Stephen Eustaquio',
    corridorTag: 'portuguese-leamington',
    birthplace: 'Leamington, Ontario',
    birthLatLng: [42.0529, -82.5990],
    transitPoint: 'Portugal (returned at age 7)',
    transitLatLng: [41.1579, -8.6291],
    canadianCity: 'Leamington',
    canadianLatLng: [42.0529, -82.5990],
    finalLatLng: [41.1579, -8.6291],
    arrivalYear: 1996,
    pathway: 'Leamington Minor Soccer -> Nazarenos (Portugal) -> Torreense -> Leixoes -> Chaves -> Cruz Azul (loan) -> Pacos de Ferreira -> Porto',
    bypassedSystem: true,
    story: 'Born in Leamington, Ontario, to Portuguese parents. Family returned to Portugal when he was seven. Developed entirely in the Portuguese youth system. Canada later capped him as a national-team player they had no part in producing.',
  },
  {
    id: 'kone',
    name: 'Ismael Kone',
    corridorTag: 'ivorian-montreal',
    birthplace: 'Abidjan, Cote d\'Ivoire',
    birthLatLng: [5.3600, -4.0083],
    canadianCity: 'Montreal',
    canadianLatLng: [45.5019, -73.5674],
    finalLatLng: [44.5380, 10.9356],
    arrivalYear: 2010,
    pathway: 'AS Notre-Dame-de-Grace -> CS Saint-Laurent -> CF Montreal -> Watford -> Marseille -> Rennes (loan) -> Sassuolo',
    bypassedSystem: true,
    partialBypass: true,
    story: 'Born in Abidjan, arrived in Montreal at seven. Came up through local Quebec community clubs before CF Montreal eventually integrated him. The Canadian developmental pipeline found him only after he had already developed himself. Now permanently at Sassuolo.',
  },
  {
    id: 'hoilett',
    name: 'Junior Hoilett',
    corridorTag: 'jamaican-brampton',
    birthplace: 'Brampton, Ontario',
    birthLatLng: [43.7315, -79.7624],
    canadianCity: 'Brampton',
    canadianLatLng: [43.7315, -79.7624],
    finalLatLng: [51.5557, -1.7797],
    arrivalYear: 1990,
    pathway: 'Brampton YSC -> Blackburn Rovers academy (age 13) -> QPR -> Cardiff -> Reading -> Vancouver Whitecaps -> Aberdeen -> Hibernian -> Swindon Town',
    bypassedSystem: true,
    story: 'Born in Brampton to Jamaican parents. Signed by Blackburn Rovers at age thirteen, in 2003, because the Canadian system could not develop him. Family relocated with him. Premier League debut at nineteen. Considered England eligibility before committing to Canada in 2015.',
  },
  {
    id: 'sinclair',
    name: 'Christine Sinclair',
    corridorTag: 'bc-burnaby',
    birthplace: 'Burnaby, British Columbia',
    birthLatLng: [49.2488, -122.9805],
    canadianCity: 'Burnaby',
    canadianLatLng: [49.2488, -122.9805],
    finalLatLng: [45.5152, -122.6784],
    arrivalYear: 1983,
    pathway: 'Burnaby youth clubs -> University of Portland (NCAA) -> Portland Thorns (NWSL)',
    bypassedSystem: true,
    story: 'Canada\'s all-time leading international goal-scorer, men\'s or women\'s. Came up through NCAA scholarship at Portland because Canada had no women\'s professional or developmental structure to produce her. Retired internationally in 2023, professionally after the 2024 NWSL season.',
  },
  {
    id: 'kadeisha-buchanan',
    name: 'Kadeisha Buchanan',
    corridorTag: 'jamaican-brampton',
    birthplace: 'Toronto, raised in Brampton/Mississauga',
    birthLatLng: [43.7315, -79.7624],
    canadianCity: 'Brampton',
    canadianLatLng: [43.7315, -79.7624],
    finalLatLng: [51.4816, -0.1925],
    arrivalYear: 1995,
    pathway: 'Brams United -> Erin Mills -> West Virginia (NCAA) -> Lyon -> Chelsea',
    bypassedSystem: true,
    story: 'Born in Toronto to Jamaican parents, raised in Brampton/Mississauga - the same diaspora corridor as Larin, Tajon Buchanan, Hutchinson, and Hoilett. NCAA scholarship to West Virginia, then European professional football. Extended with Chelsea through 2027.',
  },
  {
    id: 'lawrence',
    name: 'Ashley Lawrence',
    corridorTag: 'jamaican-brampton',
    birthplace: 'Toronto, raised in Caledon East',
    birthLatLng: [43.6532, -79.3832],
    canadianCity: 'Caledon East (Brampton corridor)',
    canadianLatLng: [43.8554, -79.8711],
    finalLatLng: [45.7640, 4.8357],
    arrivalYear: 1995,
    pathway: 'Brams United -> Erin Mills -> West Virginia (NCAA) -> PSG -> Chelsea -> OL Lyonnes',
    bypassedSystem: true,
    story: 'Born in Toronto, raised in Caledon East with a Jamaican father - Brampton diaspora corridor. NCAA scholarship to West Virginia, then European professional football. Moved to OL Lyonnes in summer 2025. The Canadian women\'s pipeline did not exist as a meaningful alternative.',
  },
  {
    id: 'grosso',
    name: 'Julia Grosso',
    corridorTag: 'bc-burnaby',
    birthplace: 'Vancouver, British Columbia',
    birthLatLng: [49.2827, -123.1207],
    canadianCity: 'Vancouver',
    canadianLatLng: [49.2827, -123.1207],
    finalLatLng: [41.8781, -87.6298],
    arrivalYear: 2000,
    pathway: 'Vancouver Italian Canadian SC -> Whitecaps Girls Elite -> University of Texas (NCAA) -> Juventus -> Chicago Stars',
    bypassedSystem: true,
    partialBypass: true,
    story: 'Born in Vancouver in 2000. Scored the gold-medal-winning penalty for Canada at Tokyo 2020. Came up through a mix of Vancouver youth clubs (including Whitecaps Girls Elite) and NCAA scholarship at Texas - like every Canadian woman of her generation, the U.S. college system was the de facto Canadian pipeline.',
  },
];
